name: requests_inspector
description: A Flutter package for logging API requests and accessing it by Shaking your phone to get the RequestsInspector widget on your screen.
version: 2.3.5
homepage: https://github.com/Abdelazeem777/requests_inspector

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  provider: ^6.0.5
  dio: ^5.0.0
  shake: ^2.2.0
  share_plus: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: requests_inspector
      ios:
        default_package: requests_inspector
      macos:
        default_package: requests_inspector
      windows:
        default_package: requests_inspector
      linux:
        default_package: requests_inspector
      web:
        default_package: requests_inspector
