name: requests_inspector
description: A Flutter package for logging REST-APIs and GraphQL requests and accessing it by Shaking your phone to get the RequestsInspector widget on your screen.
version: 3.3.0
homepage: https://github.com/Abdelazeem777/requests_inspector

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.15.0
  dio: ^5.0.0
  gql: ^0.14.0
  graphql: ^5.1.3
  graphql_flutter: ^5.1.2
  provider: ^6.0.5
  shake: ^2.2.0
  share_plus: ^7.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  plugin:
    platforms:
      android:
        default_package: requests_inspector
      ios:
        default_package: requests_inspector
      macos:
        default_package: requests_inspector
      windows:
        default_package: requests_inspector
      linux:
        default_package: requests_inspector
      web:
        default_package: requests_inspector
